import type { Booking, ItineraryOption, Place, Trip } from "./types";

const HOUR = 3600_000;
const DAY = 24 * HOUR;

const now = Date.now();
/** Date helper: `at(daysFromNow, hour)` in local time. */
function at(days: number, hour: number, min = 0): string {
  const d = new Date(now + days * DAY);
  d.setHours(hour, min, 0, 0);
  return d.toISOString();
}

function place(
  id: string,
  kind: Place["kind"],
  name: string,
  lat: number,
  lng: number,
  detail?: string,
): Place {
  return detail ? { id, kind, name, lat, lng, detail } : { id, kind, name, lat, lng };
}

function bookings(
  flight: [string, string, string],
  hotel: [string, string, string],
  cab: [string, string, string],
  status = "Confirmed",
): Booking[] {
  return [
    {
      id: "b-flight",
      type: "flight",
      title: flight[0],
      detail: flight[1],
      ref: flight[2],
      status,
      alternatives: [
        { title: "IndiGo 6E-6112", detail: "07:10 – 08:55 · Economy · ₹6,340" },
        { title: "Air India AI-509", detail: "09:25 – 11:10 · Economy · ₹7,120" },
      ],
    },
    {
      id: "b-hotel",
      type: "hotel",
      title: hotel[0],
      detail: hotel[1],
      ref: hotel[2],
      status,
      alternatives: [
        { title: "Lemon Tree Premier", detail: "₹5,900 / night · 2.4 km from venue" },
        { title: "Courtyard by Marriott", detail: "₹7,450 / night · 1.1 km from venue" },
      ],
    },
    {
      id: "b-cab",
      type: "cab",
      title: cab[0],
      detail: cab[1],
      ref: cab[2],
      status,
      alternatives: [
        { title: "Sedan – Uber Intercity", detail: "Dzire · ₹1,180" },
        { title: "Sedan – Savaari", detail: "Etios · ₹1,050" },
      ],
    },
  ];
}

function options(base: number, city: string, tierCap: number): ItineraryOption[] {
  return [
    {
      id: "o1",
      label: "Earliest arrival",
      costINR: base + 4200,
      doorToDoorMins: 250,
      comfort: 4,
      policyScore: 92,
      violations: [],
      flight: "IndiGo 6E-204 · 06:20 dep · Economy",
      hotel: `Novotel ${city}`,
      hotelNightlyINR: tierCap - 600,
      cab: "Sedan · Dzire",
    },
    {
      id: "o2",
      label: "Best value",
      costINR: base,
      doorToDoorMins: 320,
      comfort: 3,
      policyScore: 98,
      violations: [],
      flight: "Akasa QP-1382 · 11:05 dep · Economy",
      hotel: `Lemon Tree Premier ${city}`,
      hotelNightlyINR: tierCap - 2100,
      cab: "Sedan · Etios",
    },
    {
      id: "o3",
      label: "Most comfortable",
      costINR: base + 11800,
      doorToDoorMins: 265,
      comfort: 5,
      policyScore: 54,
      violations: [],
      flight: "Vistara UK-864 · 08:40 dep · Business",
      hotel: `Taj ${city}`,
      hotelNightlyINR: tierCap + 3400,
      cab: "SUV · Innova Crysta",
    },
    {
      id: "o4",
      label: "Shortest stay",
      costINR: base + 2600,
      doorToDoorMins: 290,
      comfort: 3,
      policyScore: 88,
      violations: ["Same-day return leaves only 40 minutes buffer after the meeting"],
      flight: "IndiGo 6E-6516 · 07:45 dep · Economy",
      hotel: "No overnight stay",
      hotelNightlyINR: 0,
      cab: "Sedan · Dzire",
    },
  ];
}

export const TRIPS: Trip[] = [
  {
    id: "TRV-2481",
    title: "Quarterly business review — Mumbai",
    purpose: "Client QBR with BFSI account team",
    city: "Mumbai",
    cityTier: "metro",
    originCity: "Bengaluru",
    startDate: at(-1, 6, 20),
    endDate: at(1, 20, 45),
    stage: "live",
    activeAgent: "live",
    lastAction: "Tracking 6E-204 · on time, gate 24B",
    weights: { time: 45, comfort: 25, cost: 30 },
    places: [
      place("p1", "airport", "Chhatrapati Shivaji Intl (BOM)", 19.0896, 72.8656, "Terminal 2"),
      place("p2", "hotel", "Trident Bandra Kurla", 19.0669, 72.8697, "₹7,800 / night"),
      place("p3", "meeting", "Nirlon Knowledge Park, Goregaon East", 19.16, 72.8672, "Tower 4, 9th floor"),
      place("p4", "restaurant", "Mahesh Lunch Home, BKC", 19.0654, 72.8614),
      place("p5", "restaurant", "Peshawri, BKC", 19.0669, 72.869),
    ],
    bookings: bookings(
      ["IndiGo 6E-204", "BLR → BOM · 06:20 – 08:05 · Economy · 14A", "PNR QJ4T2K"],
      ["Trident Bandra Kurla", "2 nights · ₹7,800 / night · Deluxe King", "HTL-99312"],
      ["Sedan · Dzire", "Airport → Hotel · 08:30 pickup", "CAB-55210"],
    ),
    options: options(24800, "Mumbai", 8000),
    selectedOptionId: "o1",
    budgetINR: 48000,
    expenses: [
      { id: "e1", category: "Flight", description: "IndiGo 6E-204 BLR–BOM", amountINR: 6340, source: "auto" },
      { id: "e2", category: "Hotel", description: "Trident BKC · 2 nights", amountINR: 15600, source: "auto" },
      { id: "e3", category: "Cab", description: "Airport transfer", amountINR: 980, source: "auto" },
    ],
    activity: [
      { id: "a1", at: at(-2, 18, 10), agent: "pretrip", text: "Locked itinerary option 'Earliest arrival' after your approval", mode: "approval" },
      { id: "a2", at: at(-1, 4, 5), agent: "live", text: "Completed web check-in, seat 14A held", mode: "auto" },
      { id: "a3", at: at(0, 7, 30), agent: "live", text: "Moved cab pickup 15 minutes earlier for Western Express traffic", mode: "auto" },
    ],
    autonomy: { discovery: "approve", pretrip: "approve", live: "approve", post: "auto" },
    discovery: {
      trigger: "Calendar: 'BFSI QBR — Mumbai' invite from Rohit Nair (CRM: Account #4412)",
      businessValue: 88,
      conflicts: [],
      policyFit: "Within grade L4 policy",
    },
    live: { flight: "6E-204 · On time · Gate 24B", cab: "Driver assigned · Suresh K · KA-01-AB-4412", hotel: "Room ready · early check-in granted", disrupted: false },
  },
  {
    id: "TRV-2492",
    title: "Vendor negotiation — Hyderabad",
    purpose: "Annual rate card negotiation with infra vendor",
    city: "Hyderabad",
    cityTier: "metro",
    originCity: "Bengaluru",
    startDate: at(1, 6, 15),
    endDate: at(2, 21, 30),
    stage: "confirmed",
    activeAgent: "pretrip",
    lastAction: "All bookings confirmed · monitoring fare drops",
    weights: { time: 40, comfort: 25, cost: 35 },
    places: [
      place("p1", "airport", "Rajiv Gandhi Intl (HYD)", 17.2403, 78.4294, "Terminal 1"),
      place("p2", "hotel", "Novotel HICC, Hitec City", 17.4665, 78.3715, "₹6,900 / night"),
      place("p3", "meeting", "Cyber Towers, HITEC City", 17.4483, 78.3813, "Level 6, Block A"),
      place("p4", "restaurant", "Ohri's Jiva Imperia", 17.4426, 78.3915),
      place("p5", "restaurant", "Bawarchi, RTC X Roads", 17.4062, 78.4992),
    ],
    bookings: bookings(
      ["IndiGo 6E-6112", "BLR → HYD · 07:10 – 08:20 · Economy · 12C", "PNR RT8M1P"],
      ["Novotel HICC", "1 night · ₹6,900 / night · Superior", "HTL-77420"],
      ["Sedan · Etios", "Airport → Hotel · 08:45 pickup", "CAB-61188"],
    ),
    options: options(19400, "Hyderabad", 8000),
    selectedOptionId: "o2",
    budgetINR: 32000,
    expenses: [],
    activity: [
      { id: "a1", at: at(-3, 11, 0), agent: "pretrip", text: "Compared 5 itineraries, recommended 'Best value'", mode: "approval" },
      { id: "a2", at: at(-2, 9, 20), agent: "pretrip", text: "Booked flight, hotel and cab", mode: "auto" },
    ],
    autonomy: { discovery: "approve", pretrip: "approve", live: "approve", post: "auto" },
    discovery: {
      trigger: "CRM task: 'Infra vendor rate card expiring' — Procurement pipeline",
      businessValue: 74,
      conflicts: [],
      policyFit: "Within grade L4 policy",
    },
    live: { flight: "6E-6112 · Scheduled", cab: "Booked", hotel: "Confirmed", disrupted: false },
  },
  {
    id: "TRV-2503",
    title: "Client review — Delhi NCR",
    purpose: "Programme steering committee with client CIO",
    city: "Delhi NCR",
    cityTier: "metro",
    originCity: "Bengaluru",
    startDate: at(12, 7, 0),
    endDate: at(14, 19, 0),
    stage: "planning",
    activeAgent: "pretrip",
    lastAction: "Built 4 ranked itinerary options · awaiting your choice",
    weights: { time: 50, comfort: 20, cost: 30 },
    places: [
      place("p1", "airport", "Indira Gandhi Intl (DEL)", 28.5562, 77.1, "Terminal 3"),
      place("p2", "hotel", "Hyatt Regency Gurgaon", 28.4415, 77.073, "₹7,600 / night"),
      place("p3", "meeting", "DLF Cyber City, Gurugram", 28.4949, 77.0885, "Building 10, Tower C"),
      place("p4", "restaurant", "Farzi Cafe, CyberHub", 28.4956, 77.0888),
      place("p5", "restaurant", "Prankster, Sector 29", 28.4604, 77.0702),
    ],
    bookings: bookings(
      ["Not booked yet", "Held: IndiGo 6E-2044 · 07:00 – 09:50", "—"],
      ["Not booked yet", "Held: Hyatt Regency Gurgaon", "—"],
      ["Not booked yet", "Sedan quote ₹1,120", "—"],
      "Pending",
    ),
    options: options(27600, "Gurugram", 8000),
    budgetINR: 55000,
    expenses: [],
    activity: [
      { id: "a1", at: at(-1, 15, 40), agent: "discovery", text: "Confirmed business case, handed off to Pre-Trip Agent", mode: "approval" },
      { id: "a2", at: at(-1, 15, 55), agent: "pretrip", text: "Generated 4 options against your time/comfort/cost weighting", mode: "auto" },
    ],
    autonomy: { discovery: "approve", pretrip: "approve", live: "approve", post: "auto" },
    discovery: {
      trigger: "Calendar: 'Steering committee — Q3' from client CIO office",
      businessValue: 91,
      conflicts: ["Internal town hall on day 2 (can join remotely)"],
      policyFit: "Within grade L4 policy · advance-booking rule met",
    },
    live: { flight: "—", cab: "—", hotel: "—", disrupted: false },
  },
  {
    id: "TRV-2510",
    title: "Delivery centre visit — Pune",
    purpose: "Quarterly delivery centre governance walkthrough",
    city: "Pune",
    cityTier: "other",
    originCity: "Bengaluru",
    startDate: at(20, 8, 0),
    endDate: at(21, 18, 0),
    stage: "discovery",
    activeAgent: "discovery",
    lastAction: "Business case drafted · needs your review",
    weights: { time: 35, comfort: 25, cost: 40 },
    places: [
      place("p1", "airport", "Pune Intl (PNQ)", 18.5793, 73.9089),
      place("p2", "hotel", "Conrad Pune", 18.5316, 73.877, "₹5,800 / night"),
      place("p3", "meeting", "Infosys Phase II, Hinjewadi", 18.5913, 73.7389, "Building 7"),
      place("p4", "restaurant", "Malaka Spice, Koregaon Park", 18.5362, 73.8931),
      place("p5", "restaurant", "Vaishali, FC Road", 18.5204, 73.8412),
    ],
    bookings: bookings(
      ["Not booked yet", "Discovery stage", "—"],
      ["Not booked yet", "Discovery stage", "—"],
      ["Not booked yet", "Discovery stage", "—"],
      "Pending",
    ),
    options: options(16800, "Pune", 6000),
    budgetINR: 30000,
    expenses: [],
    activity: [
      { id: "a1", at: at(0, 9, 10), agent: "discovery", text: "Matched calendar invite to CRM account, scored business value 63", mode: "auto" },
    ],
    autonomy: { discovery: "approve", pretrip: "approve", live: "approve", post: "auto" },
    discovery: {
      trigger: "Calendar: 'Delivery governance walkthrough' + CRM renewal milestone",
      businessValue: 63,
      conflicts: ["Overlaps with appraisal calibration (day 1, 4 pm)"],
      policyFit: "Hotel cap ₹6,000 / night applies (non-metro)",
    },
    live: { flight: "—", cab: "—", hotel: "—", disrupted: false },
  },
  {
    id: "TRV-2455",
    title: "Partner summit — Chennai",
    purpose: "Regional partner summit and two customer calls",
    city: "Chennai",
    cityTier: "metro",
    originCity: "Bengaluru",
    startDate: at(-9, 6, 0),
    endDate: at(-6, 20, 0),
    stage: "post",
    activeAgent: "post",
    lastAction: "Expense report drafted · 2 receipts missing",
    weights: { time: 30, comfort: 30, cost: 40 },
    places: [
      place("p1", "airport", "Chennai Intl (MAA)", 12.9941, 80.1709, "Terminal 1"),
      place("p2", "hotel", "Taj Coromandel", 13.0448, 80.2494, "₹7,900 / night"),
      place("p3", "meeting", "TIDEL Park, Taramani", 12.9895, 80.2483, "Conference hall 2"),
      place("p4", "restaurant", "Dakshin, Taj Coromandel", 13.0448, 80.2494),
      place("p5", "restaurant", "Murugan Idli Shop", 13.035, 80.22),
    ],
    bookings: bookings(
      ["IndiGo 6E-512", "BLR → MAA · 06:00 – 07:05 · Economy · 8D", "PNR LK2N9B"],
      ["Taj Coromandel", "3 nights · ₹7,900 / night", "HTL-40221"],
      ["Sedan · Dzire", "Airport → Hotel", "CAB-30119"],
    ),
    options: options(22400, "Chennai", 8000),
    selectedOptionId: "o2",
    budgetINR: 52000,
    expenses: [
      { id: "e1", category: "Flight", description: "IndiGo 6E-512 return", amountINR: 11800, source: "auto" },
      { id: "e2", category: "Hotel", description: "Taj Coromandel · 3 nights", amountINR: 23700, source: "auto" },
      { id: "e3", category: "Cab", description: "Local travel", amountINR: 3240, source: "auto", receiptRequired: true },
      { id: "e4", category: "Meals", description: "Team dinner (shared)", amountINR: 4600, source: "manual", receiptRequired: true },
    ],
    activity: [
      { id: "a1", at: at(-6, 21, 0), agent: "post", text: "Drafted expense report from bookings", mode: "auto" },
      { id: "a2", at: at(-5, 10, 0), agent: "post", text: "Flagged 2 missing receipts", mode: "auto" },
    ],
    autonomy: { discovery: "approve", pretrip: "approve", live: "approve", post: "auto" },
    discovery: {
      trigger: "Calendar: 'South region partner summit'",
      businessValue: 79,
      conflicts: [],
      policyFit: "Within grade L4 policy",
    },
    live: { flight: "Completed", cab: "Completed", hotel: "Checked out", disrupted: false },
  },
  {
    id: "TRV-2516",
    title: "New account pitch — Kolkata",
    purpose: "First-round pitch to a manufacturing prospect",
    city: "Kolkata",
    cityTier: "other",
    originCity: "Bengaluru",
    startDate: at(27, 7, 30),
    endDate: at(28, 20, 0),
    stage: "discovery",
    activeAgent: "discovery",
    lastAction: "Checking whether a video pitch meets the same goal",
    weights: { time: 30, comfort: 20, cost: 50 },
    places: [
      place("p1", "airport", "Netaji Subhas Chandra Bose Intl (CCU)", 22.6547, 88.4467),
      place("p2", "hotel", "ITC Sonar", 22.5417, 88.3997, "₹5,700 / night"),
      place("p3", "meeting", "Bengal Intelligent Park, Salt Lake V", 22.5726, 88.431, "Alpha block"),
      place("p4", "restaurant", "6 Ballygunge Place", 22.5236, 88.3639),
      place("p5", "restaurant", "Peter Cat, Park Street", 22.5533, 88.352),
    ],
    bookings: bookings(
      ["Not booked yet", "Discovery stage", "—"],
      ["Not booked yet", "Discovery stage", "—"],
      ["Not booked yet", "Discovery stage", "—"],
      "Pending",
    ),
    options: options(18900, "Kolkata", 6000),
    budgetINR: 28000,
    expenses: [],
    activity: [
      { id: "a1", at: at(-1, 17, 25), agent: "discovery", text: "Scored business value 58 — recommending a video pitch first", mode: "auto" },
    ],
    autonomy: { discovery: "suggest", pretrip: "approve", live: "approve", post: "auto" },
    discovery: {
      trigger: "Email: prospect RFI response deadline + CRM opportunity #7781",
      businessValue: 58,
      conflicts: ["Prospect has not confirmed an in-person slot"],
      policyFit: "Hotel cap ₹6,000 / night applies (non-metro)",
    },
    live: { flight: "—", cab: "—", hotel: "—", disrupted: false },
  },
];

export const INITIAL_DECISIONS = [
  {
    id: "d1",
    tripId: "TRV-2492",
    agent: "pretrip" as const,
    title: "Approve ₹900 hotel upgrade at Novotel HICC",
    reasoning:
      "Your meeting is at Cyber Towers, 1.2 km away. The cheaper option is 9 km away and adds ~50 minutes of travel across two days. The upgraded rate of ₹6,900 still sits under the ₹8,000 metro cap.",
    confidence: 86,
    alternatives: ["Keep Lemon Tree Premier (₹5,900, 9 km away)", "Shift meeting start by 30 minutes"],
    createdAt: at(0, 8, 5),
    status: "pending" as const,
  },
  {
    id: "d2",
    tripId: "TRV-2510",
    agent: "discovery" as const,
    title: "Travel needed, or will a video review do?",
    reasoning:
      "Business value scores 63/100. The walkthrough needs a floor visit, but the appraisal calibration on day 1 clashes. Travelling adds ₹16,800 against a ₹30,000 budget.",
    confidence: 61,
    alternatives: ["Move the trip one week later", "Send a regional lead instead", "Run it over video"],
    createdAt: at(0, 9, 12),
    status: "pending" as const,
  },
];
